version: "3.9"

services:
  qs-app:
    build: .
    container_name: qs-streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1